version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
